---
- name: Install Docker
  hosts: all
  vars_files:
    - "{{ playbook_dir }}/group_vars/vars.yaml"
  gather_facts: true
  tasks:
    - name: Update and install dependencies
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: latest

    - name: Add Docker's official GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Update the apt package index
      become: true
      apt:
        update_cache: yes

    - name: Install Docker
      become: true
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
        state: latest

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to the Docker group (optional)
      become: true
      user:
        name: "{{ username }}"
        groups: docker
        append: yes
        state: present